# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [124]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [125]:
print('Version - ', np.__version__)
np.show_config()

Version -  1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/include
    lib directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/include
    lib directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [126]:
_vec = np.zeros(10)
print(_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [127]:
print(_vec.size * _vec.itemsize)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [128]:
np.info(np.add)
# python -c "import numpy as np; help(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [129]:
_vec = np.zeros(10)
_vec[4] = 1
print(_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [130]:
_vec = np.arange(10,50)
print(_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [131]:
_vec = np.arange(0, 10)
_vec = _vec[::-1]
print(_vec)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [132]:
_vec = np.arange(9).reshape(3, 3)
print(_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [133]:
nonzero_indices = np.nonzero([1,2,0,0,4,0])
print(nonzero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [134]:
_matrix = np.eye(3)
print(_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [135]:
_arr = np.random.random((3,3,3))
print(_arr)

[[[0.65544276 0.3091568  0.65767942]
  [0.8360777  0.70105025 0.48568242]
  [0.76594988 0.45845261 0.18796412]]

 [[0.78010547 0.23635984 0.75013295]
  [0.17826813 0.18451252 0.68647372]
  [0.90744803 0.50680611 0.20409306]]

 [[0.97438909 0.00903318 0.16495723]
  [0.01220522 0.15199958 0.85424336]
  [0.02633926 0.41571391 0.33706594]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [136]:
Arr = np.random.random((10,10))
Arrmin, Arrmax = Arr.min(), Arr.max()
print(Arrmin, Arrmax)

0.005574174131001364 0.9694311565826373


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [137]:
_vec = np.random.random(30)
_mean = _vec.mean()
print(_mean)

0.4629354257186984


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [138]:
_arr = np.ones((10,10))
_arr[1:-1,1:-1] = 0
print(_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [139]:
_arr = np.ones((5, 5))
_arr = np.pad(_arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(_arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [140]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [141]:
_matrix = np.diag(1 + np.arange(4),k = -1)
print(_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [142]:
_matrix = np.zeros((8, 8), dtype = int)
_matrix[1::2,::2] = 1
_matrix[::2,1::2] = 1
print(_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [143]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [144]:
_arr = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(_arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [145]:
_matrix = np.random.random((5,5))
_matrix = (_matrix - np.mean(_matrix)) / (np.std(_matrix))
print(_matrix)

[[ 0.55061752  1.25916913 -1.14282747  0.61977254  0.61503834]
 [ 1.44633978 -0.79873321  1.40182681  1.23005096 -0.58395146]
 [-1.05742969 -0.62291041 -0.51547367  1.10596957 -0.92287537]
 [ 1.59150154 -0.65113446 -0.77739084 -1.21048468  0.89859449]
 [-0.96162497 -1.12018665 -0.56302845 -0.96656907  1.17573972]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [146]:
_color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [147]:
_matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
print(_matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [148]:
_arr = np.arange(11)
_arr[(3 < _arr) & (_arr < 8)] *= -1
print(_arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [149]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [150]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [151]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ -9.  -3.  10.  -3.  -5.   2.   8. -10.   2.   8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [152]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 3 4 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [153]:
defaults = np.seterr(all = "ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [154]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [155]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [156]:
_dates = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [157]:
A = np.ones(1) * 1
B = np.ones(1) * 2
np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

print(A)

[-1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [158]:
_arr = np.random.uniform(0,10,10)

print(np.floor(_arr))
print(_arr - _arr % 1)
print(np.trunc(_arr))
print(_arr.astype(int))
print(_arr // 1)

[3. 6. 3. 6. 8. 1. 6. 3. 3. 9.]
[3. 6. 3. 6. 8. 1. 6. 3. 3. 9.]
[3. 6. 3. 6. 8. 1. 6. 3. 3. 9.]
[3 6 3 6 8 1 6 3 3 9]
[3. 6. 3. 6. 8. 1. 6. 3. 3. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [159]:
_matrix = np.zeros((5,5))
_matrix += np.arange(5)
print(_matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [160]:
def generate():
    for x in range(10):
        yield x
_arr = np.fromiter(generate(),dtype = float,count = -1)
print(_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [161]:
_vec = np.linspace(0, 1, 11,endpoint = False)[1:]
print(_vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [162]:
_vec = np.random.random(10)
_vec.sort()
print(_vec)

[0.04841106 0.22296266 0.47393537 0.47596327 0.49268715 0.63779704
 0.82207395 0.94273435 0.97731822 0.99415462]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [163]:
_arr = np.arange(10)
np.add.reduce(_arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [164]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal = np.array_equal(A, B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [165]:
_arr = np.zeros(10)
_arr.flags.writeable = False
#_arr[0] = 1 # will be an error
print(_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [166]:
_matrix = np.random.random((10,2))
X,Y = _matrix[:,0], _matrix[:,1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.53189973 0.40597312 0.60116483 0.78468804 0.1373962  0.32120563
 0.72200575 0.73221414 0.59070971 0.40855284]
[1.51980297 1.46548667 1.02914699 1.40812133 1.10379111 1.21869634
 1.38995968 0.06125648 1.21778763 0.74653473]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [167]:
_vec = np.random.random(10)
_vec[_vec.argmax()] = 0
print(_vec)

[0.43595221 0.1839162  0.25750302 0.0776728  0.04456387 0.65817845
 0.         0.46366561 0.59694585 0.67948059]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [168]:
_arr = np.zeros((5,5), [('x', float), ('y', float)])
_arr['x'], _arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(_arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [169]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [170]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [171]:
np.set_printoptions(threshold = float("inf"))
_arr = np.zeros((40, 40))
print(_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [172]:
_vec = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(_vec - v)).argmin()
print(_vec[index])

47


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [173]:
_arr = np.zeros(5, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(_arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


C:\Users\Shevchenko\AppData\Local\Temp\ipykernel_8580\1932118594.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _arr = np.zeros(5, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [174]:
_vec = np.random.random((10, 2))
X,Y = np.atleast_2d(_vec[:,0], _vec[:,1])
D = np.sqrt( (X - X.T) ** 2 + (Y - Y.T) ** 2)
print(D)

[[0.         0.28252978 0.6804576  0.58154115 0.36645197 0.41870174
  0.30723109 0.17548847 0.59612643 0.31235642]
 [0.28252978 0.         0.96205079 0.83629669 0.64395156 0.57222862
  0.21530478 0.45710838 0.76646498 0.59348695]
 [0.6804576  0.96205079 0.         0.40773131 0.32331621 0.71935532
  0.91463133 0.50509633 0.61915858 0.3835475 ]
 [0.58154115 0.83629669 0.40773131 0.         0.41679859 0.38282648
  0.88474965 0.45750783 0.86290077 0.31922798]
 [0.36645197 0.64395156 0.32331621 0.41679859 0.         0.53982154
  0.59281637 0.1934347  0.44882225 0.14142521]
 [0.41870174 0.57222862 0.71935532 0.38282648 0.53982154 0.
  0.70236796 0.42386809 0.94110148 0.39947417]
 [0.30723109 0.21530478 0.91463133 0.88474965 0.59281637 0.70236796
  0.         0.44102635 0.59219893 0.59140601]
 [0.17548847 0.45710838 0.50509633 0.45750783 0.1934347  0.42386809
  0.44102635 0.         0.51791656 0.15039623]
 [0.59612643 0.76646498 0.61915858 0.86290077 0.44882225 0.94110148
  0.59219893 0.51791

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [175]:
_arr = (np.random.rand(10)*100).astype(np.float32)
Y = _arr.view(np.int32)
Y[:] = _arr
print(Y)

[73 75 44 49 40 74 87  3 77 69]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [176]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')

_file = np.genfromtxt(s, delimiter = ",")
print(_file)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [177]:
_arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(_arr):
    print(index, value)
for index in np.ndindex(_arr.shape):
    print(index, _arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [178]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [179]:
n = 10
p = 3
_arr = np.zeros((n,n))
np.put(_arr, np.random.choice(range(n * n), p, replace = False), 1)
print(_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [180]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis = 1, keepdims = True)

Y = X - X.mean(axis = 1).reshape(-1, 1)

print(Y)

[[-0.09026704  0.35514075  0.28729774 -0.08945125 -0.11833414 -0.56636605
   0.14968146 -0.46428625  0.17114979  0.36543499]
 [-0.13936835 -0.17702133  0.03476926  0.32026384 -0.29113344  0.39189556
  -0.25733339  0.1324395   0.26395688 -0.27846853]
 [-0.27530628 -0.29595649  0.30826132  0.28015699  0.29778544  0.07186286
  -0.34188288 -0.1035188  -0.0455954   0.10419326]
 [ 0.18390983 -0.31820681 -0.08658215  0.32817281 -0.05617133 -0.43233427
   0.2556171   0.25265976  0.2801505  -0.40721544]
 [ 0.25527538 -0.12025789 -0.15772115 -0.16025076 -0.169973   -0.20709764
   0.34909528  0.13514346 -0.20987146  0.28565779]]


#### 59. How to sort an array by the nth column? (★★☆)

In [181]:
_arr = np.random.randint(0,10,(3,3))
print(_arr)
print(_arr[_arr[:,1].argsort()])

[[0 9 5]
 [6 8 0]
 [9 6 8]]
[[9 6 8]
 [6 8 0]
 [0 9 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [182]:
_arr = np.random.randint(0, 3, (3, 10))
print((~_arr.any(axis = 0)).any())

# null : np.nan
_arr = np.array([
    [0, 1, np.nan],
    [1, 2, np.nan],
    [4, 5, np.nan]
])
print(np.isnan(_arr).all(axis = 0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [183]:
_arr = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

inf


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [184]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [185]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")

print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [186]:
_vec = np.ones(10)
I = np.random.randint(0, len(_vec), 20)
_vec += np.bincount(I, minlength = len(_vec))
print(_vec)


[2. 2. 4. 3. 1. 4. 5. 3. 4. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [187]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [188]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis = 0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [189]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[72 59 54 52]
 [57 53 67 42]
 [62 72 56 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [190]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43043654 0.58802884 0.63208228 0.25831766 0.39737435 0.43342044
 0.54408174 0.49860628 0.50939206 0.36055181]


#### 69. How to get the diagonal of a dot product? (★★★)

In [191]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
np.sum(A * B.T, axis = 1)

array([0.87094383, 1.15841193, 1.81707792, 1.40054642, 2.5194405 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [192]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))
Z0[::nz + 1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [193]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [194]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [195]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2 ,axis = 1), -1, axis = 1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis = 1)
G = F.view(dtype = [('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 1, 24) ( 1, 79) ( 2, 37) ( 2, 72) ( 5, 19) ( 5, 59) (14, 67) (14, 90)
 (19, 59) (24, 79) (30, 44) (30, 46) (30, 88) (30, 95) (32, 76) (32, 97)
 (33, 62) (33, 64) (37, 72) (44, 95) (46, 88) (49, 69) (49, 74) (62, 64)
 (67, 90) (69, 74) (71, 84) (71, 96) (76, 97) (84, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [196]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [197]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [198]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [199]:
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out = Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out = Z)

array([-0.69860232, -0.51047993,  0.33858386,  0.46606675, -0.09908919,
        0.88238066,  0.03640063,  0.36910985, -0.25188835,  0.39055144,
       -0.38974521, -0.18541547,  0.99270007, -0.37838464, -0.6378901 ,
        0.36118552,  0.39108339,  0.85636948,  0.94833374,  0.12578104,
        0.81758554, -0.80168814,  0.66024714,  0.73294927, -0.023582  ,
        0.6905609 , -0.6285961 , -0.25307012,  0.66096325, -0.61397792,
       -0.46707048,  0.85920582,  0.22730499,  0.38647853,  0.98616734,
       -0.3508482 ,  0.12314416, -0.08517416,  0.67857096,  0.00284934,
        0.9695696 ,  0.07147065,  0.92218786, -0.33475015, -0.66877015,
        0.73761315,  0.73747142,  0.95090012, -0.50606174, -0.64543072,
        0.26295857,  0.41260928,  0.13852443,  0.54996942, -0.71420972,
       -0.78433478,  0.70197769, -0.99783052,  0.56139443, -0.74173502,
       -0.69315422,  0.20306305,  0.57563971, -0.84895762,  0.75734916,
        0.55873616, -0.85737197, -0.5464637 , -0.83089504,  0.15

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [200]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.46139346 6.38232535 3.0822949  5.24373596 2.35121786 7.7393688
 5.67022458 6.58697245 2.18010737 4.75816596]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [201]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[10.79033108  2.05333133  3.9879987   6.41616339  5.60000817 12.505454
   1.18475153 10.28938647  1.00414387  7.27739059]
 [ 1.0817258   1.76605778  7.87457147  2.7753772   6.14658992  2.8527922
   8.04745966  8.58036065  4.0392686   4.64504998]
 [ 6.71357154  2.43247931  3.6063273   2.93163395  3.08303938  8.49455953
   2.3451144  13.38147583  6.29782621  0.82960288]
 [11.83409948  1.08173167  4.66323044  7.49048778  6.00155804 13.55293926
   2.25695871 11.3480455   0.35578771  7.84709607]
 [ 0.86822678  0.78251428 10.81137407  4.54191878  9.30134395  0.92306312
   9.82816338  9.04514172  6.15178047  7.69728086]
 [ 3.1640377   1.24515671  5.67898135  0.75390917  4.12765767  4.92875988
   6.02103953  9.45530739  3.6493602   2.50167733]
 [13.24616352  2.28818439  4.34626128  9.12052141  4.77874731 14.9899847
   3.8708217  14.57418792  2.96248009  7.15779769]
 [ 1.84625255  9.10293671  7.00827929  6.18533327  3.31100302  0.13037602
  11.42162455  1.58603789  3.25603381  2.96771513]
 [ 2

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [202]:
#---

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [203]:
Z = np.arange(1,15,dtype = np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [204]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [205]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [206]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[1 1 1]
   [3 3 0]
   [4 2 1]]

  [[1 1 4]
   [3 0 0]
   [2 1 2]]

  [[1 4 0]
   [0 0 2]
   [1 2 4]]

  [[4 0 3]
   [0 2 0]
   [2 4 3]]

  [[0 3 4]
   [2 0 3]
   [4 3 2]]

  [[3 4 2]
   [0 3 3]
   [3 2 1]]

  [[4 2 1]
   [3 3 3]
   [2 1 1]]

  [[2 1 1]
   [3 3 4]
   [1 1 4]]]


 [[[3 3 0]
   [4 2 1]
   [4 1 2]]

  [[3 0 0]
   [2 1 2]
   [1 2 1]]

  [[0 0 2]
   [1 2 4]
   [2 1 0]]

  [[0 2 0]
   [2 4 3]
   [1 0 2]]

  [[2 0 3]
   [4 3 2]
   [0 2 1]]

  [[0 3 3]
   [3 2 1]
   [2 1 2]]

  [[3 3 3]
   [2 1 1]
   [1 2 2]]

  [[3 3 4]
   [1 1 4]
   [2 2 2]]]


 [[[4 2 1]
   [4 1 2]
   [3 1 2]]

  [[2 1 2]
   [1 2 1]
   [1 2 2]]

  [[1 2 4]
   [2 1 0]
   [2 2 0]]

  [[2 4 3]
   [1 0 2]
   [2 0 3]]

  [[4 3 2]
   [0 2 1]
   [0 3 1]]

  [[3 2 1]
   [2 1 2]
   [3 1 2]]

  [[2 1 1]
   [1 2 2]
   [1 2 0]]

  [[1 1 4]
   [2 2 2]
   [2 0 1]]]


 [[[4 1 2]
   [3 1 2]
   [4 0 0]]

  [[1 2 1]
   [1 2 2]
   [0 0 1]]

  [[2 1 0]
   [2 2 0]
   [0 1 1]]

  [[1 0 2]
   [2 0 3]
   [1 1 3]]

  [[0 2 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [207]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5 12  9  8  1]
 [12  6  6  8  9]
 [ 9  6  1 42 15]
 [ 8  8 42  8 11]
 [ 1  9 15 11  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [208]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [209]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [210]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  1 0 0 0 0 0 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1
  0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 1 1 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 1 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [211]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [212]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [213]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [214]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.44 s ± 553 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
550 ms ± 48.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
313 ms ± 35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [215]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [216]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis = 1)
U = Z[~E]
print(U)


[[0 3 3]
 [2 0 4]
 [1 0 4]
 [3 4 0]
 [2 0 1]
 [2 1 1]
 [1 4 4]
 [2 2 0]
 [2 0 2]
 [0 3 4]]
[[0 3 3]
 [2 0 4]
 [1 0 4]
 [3 4 0]
 [2 0 1]
 [2 1 1]
 [1 4 4]
 [2 2 0]
 [2 0 2]
 [0 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [217]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [218]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index = True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [219]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[2.16662000e-01, 6.34434623e-02, 1.02407997e-01, 1.67193512e-01,
        3.05558061e-02, 6.89064149e-02, 1.68514206e-01, 3.02591749e-01,
        1.15462251e-02, 2.13858480e-01],
       [2.25536451e-01, 6.60420993e-02, 1.06602617e-01, 1.74041740e-01,
        3.18073685e-02, 7.17288139e-02, 1.75416529e-01, 3.14985873e-01,
        1.20191572e-02, 2.22618099e-01],
       [1.65675311e-01, 4.85134234e-02, 7.83085021e-02, 1.27848156e-01,
        2.33651618e-02, 5.26907890e-02, 1.28858053e-01, 2.31383363e-01,
        8.82907217e-03, 1.63531538e-01],
       [1.01577970e-02, 2.97442934e-03, 4.80120943e-03, 7.83855846e-03,
        1.43255243e-03, 3.23054977e-03, 7.90047677e-03, 1.41864543e-02,
        5.41323400e-04, 1.00263591e-02],
       [1.37018205e-01, 4.01219841e-02, 6.47633636e-02, 1.05734069e-01,
        1.93236549e-02, 4.35767846e-02, 1.06569284e-01, 1.91360637e-01,
        7.30189437e-03, 1.35245244e-01],
       [4.44024445e-01, 1.30020253e-01, 2.09873692e-01, 3.42644333e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [220]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x) ** 2 + np.diff(y) ** 2) ** .5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [221]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [222]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14434483  0.27656873]
