# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [223]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [224]:
print('Version - ', np.__version__)
np.show_config()

Version -  1.26.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/include
    lib directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/include
    lib directory: C:/Users/Shevchenko/.conda/envs/Labs/Library/lib
    name: mkl-sdl
    pc file directory: C:\b\abs_9fu2cs2527\croot\numpy_and_numpy_base_1695830496596\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [225]:
_vec = np.zeros(10)
print(_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [226]:
print(_vec.size * _vec.itemsize)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [227]:
np.info(np.add)
# python -c "import numpy as np; help(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [228]:
_vec = np.zeros(10)
_vec[4] = 1
print(_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [229]:
_vec = np.arange(10,50)
print(_vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [230]:
_vec = np.arange(0, 10)
_vec = _vec[::-1]
print(_vec)

[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [231]:
_vec = np.arange(9).reshape(3, 3)
print(_vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [232]:
nonzero_indices = np.nonzero([1,2,0,0,4,0])
print(nonzero_indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [233]:
_matrix = np.eye(3)
print(_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [234]:
_arr = np.random.random((3,3,3))
print(_arr)

[[[0.91654936 0.51709253 0.38420534]
  [0.22229865 0.53713354 0.05007132]
  [0.71623833 0.68931169 0.44993464]]

 [[0.04162685 0.28041001 0.93793332]
  [0.89727216 0.71055398 0.71274589]
  [0.12972599 0.83107318 0.25247192]]

 [[0.21509709 0.11599044 0.17304646]
  [0.78570287 0.4043457  0.68222709]
  [0.88519314 0.68940158 0.71581599]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [235]:
Arr = np.random.random((10,10))
Arrmin, Arrmax = Arr.min(), Arr.max()
print(Arrmin, Arrmax)

0.0022934339358087197 0.9958178752755764


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [236]:
_vec = np.random.random(30)
_mean = _vec.mean()
print(_mean)

0.5542987721517598


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [237]:
_arr = np.ones((10,10))
_arr[1:-1,1:-1] = 0
print(_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [238]:
_arr = np.ones((5, 5))
_arr = np.pad(_arr, pad_width = 1, mode = 'constant', constant_values = 0)
print(_arr)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [239]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [240]:
_matrix = np.diag(1 + np.arange(4),k = -1)
print(_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [241]:
_matrix = np.zeros((8, 8), dtype = int)
_matrix[1::2,::2] = 1
_matrix[::2,1::2] = 1
print(_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [242]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [243]:
_arr = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(_arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [244]:
_matrix = np.random.random((5,5))
_matrix = (_matrix - np.mean(_matrix)) / (np.std(_matrix))
print(_matrix)

[[-1.65266069  0.30016094 -0.96649553 -1.2547215   0.31219333]
 [-0.05013683  1.65100642  1.4376492   0.95357416 -0.98222696]
 [ 1.03928223 -1.62686494 -0.45695701 -0.13108326 -0.51298495]
 [-1.2616789   0.06417946  0.71730978 -0.04510177  0.92421708]
 [-0.74773938  1.62883086  0.79107578 -1.03346946  0.90264194]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [245]:
_color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [246]:
_matrix = np.dot(np.ones((5,3)), np.ones((3,2)))
print(_matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [247]:
_arr = np.arange(11)
_arr[(3 < _arr) & (_arr < 8)] *= -1
print(_arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [248]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

TypeError: 'numpy.ndarray' object is not callable

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [249]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [250]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-6. -7. -9.  2. -6. -6. 10. -1.  8. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [251]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 4 5 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [252]:
defaults = np.seterr(all = "ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [253]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [254]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [255]:
_dates = np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')
print(_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [256]:
A = np.ones(1) * 1
B = np.ones(1) * 2
np.add(A, B, out = B)
np.divide(A, 2, out = A)
np.negative(A, out = A)
np.multiply(A, B, out = A)

print(A)

[-1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [257]:
_arr = np.random.uniform(0,10,10)

print(np.floor(_arr))
print(_arr - _arr % 1)
print(np.trunc(_arr))
print(_arr.astype(int))
print(_arr // 1)

[7. 2. 2. 3. 2. 4. 1. 5. 4. 0.]
[7. 2. 2. 3. 2. 4. 1. 5. 4. 0.]
[7. 2. 2. 3. 2. 4. 1. 5. 4. 0.]
[7 2 2 3 2 4 1 5 4 0]
[7. 2. 2. 3. 2. 4. 1. 5. 4. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [258]:
_matrix = np.zeros((5,5))
_matrix += np.arange(5)
print(_matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [259]:
def generate():
    for x in range(10):
        yield x
_arr = np.fromiter(generate(),dtype = float,count = -1)
print(_arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [260]:
_vec = np.linspace(0, 1, 11,endpoint = False)[1:]
print(_vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [261]:
_vec = np.random.random(10)
_vec.sort()
print(_vec)

[0.07450424 0.15538099 0.18099001 0.26663224 0.36786717 0.39089259
 0.44687374 0.58152075 0.58609988 0.64991853]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [262]:
_arr = np.arange(10)
np.add.reduce(_arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [263]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

equal = np.array_equal(A, B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [264]:
_arr = np.zeros(10)
_arr.flags.writeable = False
#_arr[0] = 1 # will be an error
print(_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [265]:
_matrix = np.random.random((10,2))
X,Y = _matrix[:,0], _matrix[:,1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.89292665 0.7772815  0.83504011 0.48030877 1.20440835 1.00577441
 0.90054484 0.57978435 0.47992618 0.93216013]
[0.44948599 0.4785709  0.08667386 0.42374007 0.83766154 1.20142317
 0.2577257  1.39518878 1.25984693 1.53013069]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [266]:
_vec = np.random.random(10)
_vec[_vec.argmax()] = 0
print(_vec)

[0.13307789 0.28316337 0.77305018 0.33679617 0.6197918  0.50039496
 0.82873721 0.         0.15856063 0.13689406]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [267]:
_arr = np.zeros((5,5), [('x', float), ('y', float)])
_arr['x'], _arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(_arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [268]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [269]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [270]:
np.set_printoptions(threshold = float("inf"))
_arr = np.zeros((40, 40))
print(_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [271]:
_vec = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(_vec - v)).argmin()
print(_vec[index])

41


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [272]:
_arr = np.zeros(5, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(_arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.))]


C:\Users\Shevchenko\AppData\Local\Temp\ipykernel_8580\1932118594.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _arr = np.zeros(5, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [273]:
_vec = np.random.random((10, 2))
X,Y = np.atleast_2d(_vec[:,0], _vec[:,1])
D = np.sqrt( (X - X.T) ** 2 + (Y - Y.T) ** 2)
print(D)

[[0.         0.59249639 0.88626697 0.85115429 0.86823072 0.39732283
  0.54487476 0.73464719 0.69043149 0.18885925]
 [0.59249639 0.         0.36844571 0.46197388 0.76995861 0.57741129
  0.66066659 0.63554705 0.4691664  0.44454036]
 [0.88626697 0.36844571 0.         0.20890494 0.63612897 0.70355524
  0.71008704 0.55125717 0.38411527 0.70519655]
 [0.85115429 0.46197388 0.20890494 0.         0.42912742 0.5839934
  0.55389722 0.35811735 0.21571989 0.66233663]
 [0.86823072 0.76995861 0.63612897 0.42912742 0.         0.47791354
  0.3479953  0.14559728 0.30170835 0.70672332]
 [0.39732283 0.57741129 0.70355524 0.5839934  0.47791354 0.
  0.14925616 0.35607655 0.37649352 0.2679276 ]
 [0.54487476 0.66066659 0.71008704 0.55389722 0.3479953  0.14925616
  0.         0.25075726 0.33841725 0.4142529 ]
 [0.73464719 0.63554705 0.55125717 0.35811735 0.14559728 0.35607655
  0.25075726 0.         0.17862903 0.56676567]
 [0.69043149 0.4691664  0.38411527 0.21571989 0.30170835 0.37649352
  0.33841725 0.178629

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [274]:
_arr = (np.random.rand(10)*100).astype(np.float32)
Y = _arr.view(np.int32)
Y[:] = _arr
print(Y)

[27 91 75 62 52 56 81 38 43 82]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [275]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')

_file = np.genfromtxt(s, delimiter = ",")
print(_file)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [276]:
_arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(_arr):
    print(index, value)
for index in np.ndindex(_arr.shape):
    print(index, _arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [277]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X * X + Y * Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [278]:
n = 10
p = 3
_arr = np.zeros((n,n))
np.put(_arr, np.random.choice(range(n * n), p, replace = False), 1)
print(_arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [279]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis = 1, keepdims = True)

Y = X - X.mean(axis = 1).reshape(-1, 1)

print(Y)

[[ 0.23464743  0.49872831  0.18090682 -0.3253686   0.16962097 -0.25204442
   0.35880496 -0.19143298 -0.21785797 -0.45600453]
 [-0.28892679 -0.1267674  -0.17578453 -0.37584437  0.44136115  0.21081117
   0.26182606  0.27415385 -0.18832826 -0.03250087]
 [-0.28067384  0.30310419  0.01307958  0.34030537  0.3224204  -0.12280923
  -0.00265757 -0.34021276  0.22288671 -0.45544285]
 [ 0.17423902 -0.14555592 -0.31699085  0.01227922  0.44262997  0.48894252
  -0.07937352  0.15072394 -0.29397032 -0.43292406]
 [-0.09407594 -0.23140634  0.31899535 -0.29023327  0.20629377 -0.33539221
  -0.28161141  0.54613925 -0.20465872  0.36594951]]


#### 59. How to sort an array by the nth column? (★★☆)

In [280]:
_arr = np.random.randint(0,10,(3,3))
print(_arr)
print(_arr[_arr[:,1].argsort()])

[[0 3 0]
 [3 6 4]
 [0 0 1]]
[[0 0 1]
 [0 3 0]
 [3 6 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [281]:
_arr = np.random.randint(0, 3, (3, 10))
print((~_arr.any(axis = 0)).any())

# null : np.nan
_arr = np.array([
    [0, 1, np.nan],
    [1, 2, np.nan],
    [4, 5, np.nan]
])
print(np.isnan(_arr).all(axis = 0))

False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [282]:
_arr = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

inf


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [283]:
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)

it = np.nditer([A,B,None])

for x,y,z in it: z[...] = x + y

print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [284]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name = "no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")

print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [285]:
_vec = np.ones(10)
I = np.random.randint(0, len(_vec), 20)
_vec += np.bincount(I, minlength = len(_vec))
print(_vec)


[2. 1. 4. 3. 3. 4. 3. 1. 6. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [286]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]

F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [287]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis = 0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [288]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[52 49 58 37]
 [63 59 50 48]
 [55 38 42 53]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [289]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.64569677 0.38982889 0.51605993 0.48915553 0.53357045 0.3957797
 0.36511935 0.57103295 0.60358723 0.48610557]


#### 69. How to get the diagonal of a dot product? (★★★)

In [290]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
np.sum(A * B.T, axis = 1)

array([1.51109572, 2.02444879, 2.17738794, 1.18017818, 0.92239344])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [291]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))
Z0[::nz + 1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [292]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [293]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [294]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2 ,axis = 1), -1, axis = 1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis = 1)
G = F.view(dtype = [('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[(10, 38) (10, 77) (11, 42) (11, 92) (17, 60) (17, 95) (18, 38) (18, 63)
 (20, 38) (20, 74) (25, 56) (25, 96) (38, 63) (38, 74) (38, 77) (42, 92)
 (43, 45) (43, 71) (45, 71) (48, 65) (48, 67) (50, 68) (50, 96) (56, 96)
 (60, 95) (62, 63) (62, 75) (63, 75) (65, 67) (68, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [295]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [296]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [297]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [298]:
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out = Z)

Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out = Z)

array([-0.1810737 ,  0.25737338, -0.12729353, -0.78670486, -0.29741777,
       -0.97779601,  0.34392803,  0.63636844, -0.51919278,  0.02395263,
        0.93941194, -0.99831188, -0.7149498 ,  0.13170297, -0.36161395,
       -0.14530156,  0.9026196 , -0.22820229,  0.17902037, -0.44220783,
       -0.49979871,  0.54211107, -0.8997687 , -0.43968625,  0.36424449,
        0.40556921, -0.96995615,  0.70467204,  0.56728005, -0.85940891,
       -0.85798664,  0.90688328, -0.92223961, -0.80935828, -0.6736127 ,
       -0.57516923, -0.68367256,  0.46014322,  0.43772304, -0.26286016,
        0.19007306,  0.1031247 , -0.74808779, -0.54122218, -0.93398201,
       -0.84274961,  0.39898093,  0.60046271,  0.70292445,  0.41170655,
       -0.91671967,  0.31442358, -0.20711017, -0.35137746, -0.16125929,
        0.79198007, -0.43881693, -0.47349569,  0.92248315,  0.13882088,
        0.11016049,  0.13730645, -0.5858138 , -0.82226219, -0.29756463,
        0.06955561,  0.66316467,  0.31449355, -0.25518093,  0.23

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [299]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.70656602  0.81202196  0.12394462  8.62867072  9.33757584  6.84678457
 12.28140464  3.8073282   3.82128462  3.96444602]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [300]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.36135368  0.33120213  2.78875344  5.66690308  5.67694121  3.45391935
   8.25609517  7.47630145  1.85989396  0.92108819]
 [ 6.04498306  2.23739139  5.74221907 11.51117151 10.47331012  5.60152089
   6.54937487  6.87407007  7.25300387  5.78824443]
 [ 8.92211131  0.49937931  3.32664841 13.63218132 13.16529675  2.93025623
   9.33667856  9.88579853  9.67076795  8.45267287]
 [11.16701819  3.41588052  0.76549718  7.14839397  8.06652146  0.25924377
  12.02677226 11.30928982  3.79518708  3.26291281]
 [ 8.84922507  1.74732742  0.33471595  0.14685696  0.95618844  1.13406233
  10.13503485  8.24713806  3.48057928  3.87291351]
 [ 5.51139241  2.24846717  4.78717205  5.94472233  5.39812846  5.39443879
   6.35995795  5.72665915  1.87092988  0.67400982]
 [ 1.56901482  4.77116899  4.62867371  9.74989875  9.60264044  7.31810895
   3.35030693  0.14414047 13.63847343 14.39817442]
 [ 4.24748776 11.27012859 12.2425288   3.97045152  6.13963496 14.08555405
   2.92198049  4.79849828  8.92487325 10.79350895]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [301]:
#---

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [302]:
Z = np.arange(1,15,dtype = np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [303]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)  
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [304]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [305]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[1 4 0]
   [3 4 3]
   [4 2 3]]

  [[4 0 2]
   [4 3 1]
   [2 3 2]]

  [[0 2 3]
   [3 1 4]
   [3 2 0]]

  [[2 3 0]
   [1 4 2]
   [2 0 0]]

  [[3 0 3]
   [4 2 1]
   [0 0 2]]

  [[0 3 2]
   [2 1 3]
   [0 2 2]]

  [[3 2 1]
   [1 3 4]
   [2 2 2]]

  [[2 1 4]
   [3 4 2]
   [2 2 4]]]


 [[[3 4 3]
   [4 2 3]
   [1 1 2]]

  [[4 3 1]
   [2 3 2]
   [1 2 2]]

  [[3 1 4]
   [3 2 0]
   [2 2 4]]

  [[1 4 2]
   [2 0 0]
   [2 4 2]]

  [[4 2 1]
   [0 0 2]
   [4 2 0]]

  [[2 1 3]
   [0 2 2]
   [2 0 3]]

  [[1 3 4]
   [2 2 2]
   [0 3 3]]

  [[3 4 2]
   [2 2 4]
   [3 3 2]]]


 [[[4 2 3]
   [1 1 2]
   [1 1 4]]

  [[2 3 2]
   [1 2 2]
   [1 4 1]]

  [[3 2 0]
   [2 2 4]
   [4 1 3]]

  [[2 0 0]
   [2 4 2]
   [1 3 4]]

  [[0 0 2]
   [4 2 0]
   [3 4 2]]

  [[0 2 2]
   [2 0 3]
   [4 2 0]]

  [[2 2 2]
   [0 3 3]
   [2 0 4]]

  [[2 2 4]
   [3 3 2]
   [0 4 3]]]


 [[[1 1 2]
   [1 1 4]
   [0 1 4]]

  [[1 2 2]
   [1 4 1]
   [1 4 0]]

  [[2 2 4]
   [4 1 3]
   [4 0 4]]

  [[2 4 2]
   [1 3 4]
   [0 4 4]]

  [[4 2 0]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [306]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9 12 11 10 12]
 [12  6  4 15  8]
 [11  4  8 42  6]
 [10 15 42  6 10]
 [12  8  6 10  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [307]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [308]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [309]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [310]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [311]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [312]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.65 s ± 516 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0, 5, (10, 3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis = 1)
U = Z[~E]
print(U)


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index = True)
uZ = Z[idx]
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)        
np.einsum('i,i->i', A, B)  
np.einsum('i,i', A, B)     
np.einsum('i,j->ij', A, B)    

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10 * np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x) ** 2 + np.diff(y) ** 2) ** .5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)     
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) 
N = 1000 

idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis = 1)

confint = np.percentile(means, [2.5, 97.5])
print(confint)